<!--
Copyright 2022 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div>
    <div id="home-heading" class="heading-section">
      {{ $t('heading[0]') }}
      <div class="logos">
        <img src="../assets/img/pmi.png" alt="PMI">
        <img src="../assets/img/moh.png" alt="MOH">
        <!-- <img src="../assets/img/pmi2.png" alt="kinga-malaria"> -->
      </div>
    </div>
    <home-summary/>
    <div id="home-news-container">
      <home-news/>
      <home-config-section v-if="config.home.title != null"
        :title="config.home.title" :body="config.home.body"/>
    </div>
    <project-list/>
  </div>
</template>

<script>
import { defineAsyncComponent } from 'vue';

import HomeNews from './home/news.vue';
import HomeSummary from './home/summary.vue';
import ProjectList from './project/list.vue';

import { loadAsync } from '../util/load-async';
import { noop } from '../util/util';

export default {
  name: 'Home',
  components: {
    HomeConfigSection: defineAsyncComponent(loadAsync('HomeConfigSection')),
    HomeNews,
    HomeSummary,
    ProjectList
  },
  inject: ['config'],
  created() {
    this.fetchData();
  },
  methods: {
    fetchData() {
      this.$store.dispatch('get', [{
        key: 'projects',
        url: '/v1/projects?forms=true'
      }]).catch(noop);
    }
  }
};
</script>

<style lang="scss">
@import '../assets/scss/variables';

#home-heading {
  background: $color-subpanel-background;
  color: $color-accent-primary;
  font-size: 35px;
  font-weight: 600;
  letter-spacing: -0.03em;
  margin-left: -15px;
  margin-right: -15px;
  padding: 20px 15px 15px 15px;

}

#home-news-container {
  display: flex;
  > * { flex: 1; }
}
</style>

<i18n lang="json5">
{
  "en": {
    "heading": [
      "PMI Kinga Malaria"
    ]
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "heading": [
      "PMI Kinga Malaria"
    ]
  },
  "de": {
    "heading": [
      "PMI Kinga Malaria"
    ]
  },
  "es": {
    "heading": [
      "PMI Kinga Malaria"
    ]
  },
  "fr": {
    "heading": [
      "PMI Kinga Malaria"
    ]
  },
  "it": {
    "heading": [
      "PMI Kinga Malaria"
    ]
  }
}
</i18n>
